databases:
  - name: tutor_selfedu
    databaseName: db
    user: admin

services:
  - type: web
    name: tutor_selfedu
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tutor_selfedu.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutor_selfedu
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4