services:
  - type: web
    name: tutor_selfedu
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tutor_selfedu.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4